### ISSUE TITLE
encoding of personal names

### ISSUE THREAD

**Issue by tuurma** [KatarinaKelsey/Antigone_Notes#1]
use of author/principal records as person records seems a bit fishy, I'd create a regular list of persons
```
<profileDesc>
 <particDesc>
  <listPerson>
   <person xml:id="MM">
    <persName><surname>Minkova</surname>, <forename>Miglena</forename></persName>
   </person>
...
```

and later only point to it from <persName> via @ref attribute

```
   <principal type="marc700">
	<persName ref="#MM"><surname>Minkova</surname>, <forename>Minkova</forename>.</persName>
   </principal>
```
btw, marking up name and surname in every reference in the header seems a bit of an overkill

**Comment by tuurma** [comment]
What follows, I'd get rid of @xml:id on principal/respStmt etc altogether, since they no longer would need to be abused as person identifiers :-)

**Comment by MMinkova** [comment]
TEI encoding updated following above recommendations.
