### ISSUE TITLE
references to people, places and organizations

### ISSUE THREAD

**Issue by tuurma** [KatarinaKelsey/Antigone_Notes#2]
there's a bit of incoherency in choosing <persName> for references to people and <name type="place"> for places (https://github.com/KatarinaKelsey/Antigone_Notes/blob/master/Antigone_Notes_TEI_Encoding.xml#L96) and similar for organizations. My recommendation would be to choose one convention and stick to it throughout, eg persName, placeName, orgName

**Comment by MMinkova** [comment]
TEI encoding updated following above recommendations.
