### ISSUE TITLE
encoding text structure

### ISSUE THREAD

**Issue by tuurma** [KatarinaKelsey/Antigone_Notes#3]
I think the simplest way to encode the text is just go for `div` elements representing the four booklets

so

```
<TEI>
<teiHeader>...</teiHeader>
<text>
<front>
...possibly put the text from front part of the cover here...
</front>
<body>
<div type="booklet" n="1">
content of the first booklet
</div>
...
</body>
<back>
...back part of the cover?...
</back>
</text>
</TEI>
```

alternatively the cover parts could just be divs. Going the way of TEI Corpus seems a bit too much, given that the source text is in fact a single book. 

Depending what kind of metadata you need for the booklets, there's probably a good way to fit them in the header, just pointing to the id of booklet in question, perhaps using msPart for it.

Last remark, `<pb>` elements should belong to a div, not be stuck between them.

```<div type="booklet" n="1" xml:id="B1">
<pb facs="img5.jpg" n="5">
<p rendition="r-indent">Hence, as already touched upon in the notes on 
<persName ref="#oedipus">Oedipus</persName>, the dia-<lb break="no"/>
                  logic form and the chorus as its antithesis, hence also the dangerous<lb/>
                  form in the scenes, which, in a way more characteristic of the Greeks,<lb/>
....
```

**Comment by MMinkova** [comment]
If I use following structure, are the `<pb>` inside divs?
```
<div type="booklet" n="1"> 
<pb/>
<p> some text</p>
<pb/>
<p> soem text</p>
</div>
```

**Comment by MMinkova** [comment]
Page breaks nestled in divs
